#!/usr/bin/env ruby
module LMAO
(65..90).map(&:chr).each {|_a|
eval "#{_a} = ->{$#{_a}||=0;$#{_a}=$#{_a}.succ;const_get(:'#{_a}')}"}
eval (::DATA.read)
end

__END__
const_get(%^A^).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
const_get(%%B%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call
const_get(%%C%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call
const_get(%%D%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call
const_get(%%E%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call
const_get(%%F%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call
const_get(%%G%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
const_get(%%H%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call
const_get(%%I%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call
const_get(%%J%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call
const_get(%%K%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call
const_get(%%L%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call
const_get(%%M%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call
const_get(%%N%).call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
.call.call.call.call.call.call.call.call
